Fix `Deployment` model definition (#271)
#258 added fields to the `Deployment` model provided by the new
`deployments.{get,list,update}` endpoints. However, those were
implemented against a version of the OpenAPI specification that
disagreed with the actual API responses. Specifically, the
`min_instances` and `max_instances` properties were listed as
subproperties of a `scaling` object rather than direct fields. The
result — as reported in #270 — was Pydantic validation errors like this:

```
raise validation_error
pydantic.v1.error_wrappers.ValidationError: 1 validation error for Deployment
current_release -> configuration -> scaling
field required (type=value_error.missing)"
```

This PR updates the `Deployment` model to correctly locate
`min_instances` and `max_instances` as properties of
`current_release.configuration`.

Signed-off-by: Mattt Zmuda <mattt@replicate.com>